server {
    listen 80;
    server_name campusync.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name campusync.tech;
    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/users {
        proxy_pass http://auth-service:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/complaints {
        proxy_pass http://complaint-service:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/lost-found {
        proxy_pass http://lost-found-service:8083;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/notifications {
        proxy_pass http://notification-service:8084;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
