services:

  postgres:
    image: postgres:16
    container_name: hostelhub-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hostelhub-network

  kafka:
    image: apache/kafka:3.7.0
    container_name: hostelhub-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"
    networks:
      - hostelhub-network

  eureka-server:
    build: ./eureka-server
    container_name: hostelhub-eureka
    ports:
      - "8761:8761"
    networks:
      - hostelhub-network

  auth-service:
    build: ./auth-service
    container_name: hostelhub-auth
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hostelhub_auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - eureka-server
    networks:
      - hostelhub-network

  complaint-service:
    build: ./complaint-service
    container_name: hostelhub-complaint
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hostelhub_complaint
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - kafka
      - eureka-server
    networks:
      - hostelhub-network

  lost-found-service:
    build: ./lost-found-service
    container_name: hostelhub-lostfound
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hostelhub_lostfound
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - eureka-server
    networks:
      - hostelhub-network

  notification-service:
    build: ./notification-service
    container_name: hostelhub-notification
    ports:
      - "8084:8084"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - kafka
      - eureka-server
    networks:
      - hostelhub-network

  api-gateway:
    build: ./api-gateway
    container_name: hostelhub-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - auth-service
      - complaint-service
      - lost-found-service
      - notification-service
    networks:
      - hostelhub-network

  frontend:
    build: ./frontend
    container_name: hostelhub-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - hostelhub-network

volumes:
  postgres-data:

networks:
  hostelhub-network:
    driver: bridge
